# Let's start with a brief definition of machine learning just as a reminder

> ML is turning any data  into numbers and finding patterns in those numbers

This notes are code focus, so the math will be handled behind the scene.

- For now just consider the basic paradigm behind ML vs traditional programming: **ML** receives inputs and outputs to figure out rules (over-simplification), while **traditional programming** receive inputs and rules that guide to an output.

**You might want to use ML and DL for:**
- Problems with lon lists of rules
- Continually changing environments
- Discovering insights within large sets of data

**You might not want to use ML and DL for:**
- Need explainability — the patterns learned are usually uninterpretable by a human
- When traditional programming offers better results
- When errors are unacceptable
- When there is not a lot of data (unless you have a specific approach to this)

**Typically you will:**
- Use ML for structured data
- Use DP for unstructured data

_However, depending on how you represent your problem, you can use either ML or DL algorithms to solve it_

**Anatomy of Neural Networks:**
* Input layer: data goes here
* Hidden Layer(s): learns patterns in data (numerical representations) from a set number of neurons
>'Patterns' is an arbitrary term used interchangeably with 'embedding', 'weights', 'feature representation', 'feature vectors', all referring to similar things.
* Output layers: output learned representation or prediction probabilities

_There are some very complex architectures (Like the computer vision's popular resnet152 which has 152 hidden layers) as there are single hidden layered NN._ Each layer is usually combination of linear (straight line) and/or non-linear (non-straight line) functions.

## Types of learning

- Supervised: Has data with labels for all
- Semi-supervised: Some data with labels used to train a model that would then be used to train the data without labels
- Unsupervised: Data with no labels (idk what is in the dataset, so look what you can find)
- Transfer: When a model has learned patterns from a set of data, those patterns can be used in another problem for another set of data
- Reinforcement learning: using a system of action and reward to feed the NN

## What is Deep Learning actually used for

>💡 Start looking almost every experience as something that can be translated into numbers and how to actually do that

- ****Some use cases:****
    - Recommendation
    - Translation
    - Speech recognition
    - Computer vision
    - NLP
- ****************Deepmind :**************** They converted proteins to numbers and there the patterns were hidden

## What is PyTorch
> Most popular research deeplearning framework, able to run on GPU/GPUs and access many pre-built deep learning models.
- It is whole stack: preprocess data, model data, deploy model in app/cloud
- Originally designed and used in-house by Meta(formerly Facebook), now open-source and used by companies such such as Tesla, Microsoft, openAI.

## Why Pytorch?
> Other than being used by 58% of papers up to dec 2021, this is a tool that allows virtually anyone solve problems that would have taken a whole team and lots of investment back in 2014
Some players in AI using pytorch are:
- [Tesla](https://youtu.be/oBklltKXtDE)
- [OpenAI](https://openai.com/blog/openai-pytorch)
- [The incredible PyTorch project](https://github.com/NurmaU/incredible_pytorch)
- _AND_ it allows to run code on GPU (using CUDA based interfaces used for general purpose computing that allow tu run numerical computations)

## What is a tensor?
> You have inputs, representations, and outputs: all numerically encoded. Therefore, a tensor is any kind of n-rank, m-dimensional numerical encoding used to represent data in a way that a human would not understand though a computer would.
_However, a tensor is not a fixed concept ([for a broad yet comprehensive explanation check this out](https://www.youtube.com/watch?v=f5liqUk0ZTw))_

## So, the roadpath (or so I expect, remember life laughs at previsions):
* Dealing with tensors and tensor operations (Just like we did in TensorFlow)
* Preprocessing Data (getting it into tensors)
* Building and using pretrained DL models
* Fitting a model to data (learning patterns)
* Making predictions with a model (using models)
* Evaluating model predictions
* Saving and loading models
* Using a trained model to make predictions on custom data
### How: we are cooks, not chemists.
> A little bit of science, a little bit of art.
## A PyTorch Workflow (taken from ZtM)
![Screenshot 2023-09-24 at 13.11.52.png](<attachment:Screenshot 2023-09-24 at 13.11.52.png>)
### But how do I approach AI?
> Learning and coding AI are two different things. Either focus on coding along this course notes, explore and experiment, visualize what you don't understand, ask questions, whatever you choose, justo go for it. But most importantly: _**Do something and share your work**_

Please, avoid the "I can't learn" mindset, burning yourself out is no good for your brain.

## Here is where the code starts so hold on tight, we are done with the nice titles and friendly definitions, lol

Btw, the markdown notes are currently being written in vscode while the code is wrote and executed in Colab Notebooks.

In [1]:
# Let's import all necessary libraries for our runtime
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__) # Check the torch version we are working with

# We won't be using GPUs just yet. Let's go step by step

2.0.1+cu118


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html


In [2]:
# scalar // There are different types of tensors
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# Check the dimensions of a tensor
scalar.ndim # A 0D tensor is nothing but a scalar

0

In [4]:
# As a result, a scalar can be reached as a singular Python int
scalar.item()

7

In [5]:
# Create a vector // has a magnitude and a dimension and is >1 number
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim # 1D, one way to check it is the number of pairs of closing square brackets

1

In [7]:
vector.shape # It is different to the dimension as it is the numbers of elements inside each dimension

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([
    [7,8],
    [9,10]
])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim # Matrix are 2 dimensional

2

In [10]:
MATRIX.shape # This will output the elements in each dimension from outer to inner

torch.Size([2, 2])

In [11]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]]) # Most times you won't do this manually, just understand how this fundamentally works
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
 TENSOR.ndim

3

In [13]:
TENSOR.shape # Again, here the dimension 0 [outtest pair of brackets] has 1 element, dimension 1 has 3 and dimension 2 has 3

torch.Size([1, 3, 3])

In [14]:
TENSOR[0], TENSOR[0][1][2] # Each element is indexed from zero just as usual

(tensor([[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]),
 tensor(9))

> A Tensor can be of almost any shape and size

Typically, lowecase variable names are scalar or vectors while uppercase variables are Matrix or tensors
### Random Tensors

These are important because many NN start with random numbers and adjust those random numbers to better represent the data:

`start with random numbers->look at data->update random numbers->look at data-> update random numbers->and so on till we've got a valuable result`

Docs for [torch.rand()](https://pytorch.org/docs/stable/generated/torch.rand.html?highlight=rand#torch.rand)

In [15]:
# Create a random tensor of size/shape (same in PyTorch)
random_tensor = torch.rand(1,3,4) # There can be whatever number inside of this
random_tensor

tensor([[[0.1386, 0.7440, 0.9878, 0.5108],
         [0.5321, 0.8450, 0.2677, 0.6699],
         [0.0888, 0.1059, 0.4332, 0.8291]]])

In [16]:
random_tensor.ndim

3

In [17]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels, doesn't matter if color channels go first or last (the importance here is in data representation as numbers)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [18]:
# Playing with torch.rand()
random_2 = torch.rand(4,4,2) # torch.rand(size=(x,y,z)) is optional as size is the default parameter
random_2.shape, random_2.ndim, random_2

(torch.Size([4, 4, 2]),
 3,
 tensor([[[0.4426, 0.0127],
          [0.2551, 0.0558],
          [0.1676, 0.1585],
          [0.7066, 0.8128]],
 
         [[0.9551, 0.1249],
          [0.9956, 0.8754],
          [0.4633, 0.3014],
          [0.4179, 0.8220]],
 
         [[0.5612, 0.1607],
          [0.4615, 0.4341],
          [0.0792, 0.1077],
          [0.5190, 0.9709]],
 
         [[0.1212, 0.6068],
          [0.2011, 0.3566],
          [0.8561, 0.0662],
          [0.2991, 0.0978]]]))

### Zeros and Ones

In [19]:
# Create a tensor of all zeros (useful to create masks, don't worry we'll get back to that in a second)
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4)) # zeros is more common than ones, though usually random tensors are the most used
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
zeros.dtype, ones.dtype # Check the data type of each tensor, defaults to torch.float32

(torch.float32, torch.float32)

### Creating a range of tensors and tensors-like

In [22]:
# use torch.range()
torch.range(1,10) # This one is deprecated and won't work properly in the future

<ipython-input-22-8a5363e3a320>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,10) # This one is deprecated and won't work properly in the future


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [23]:
# Better use torch.arange()!!!
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# Creating tensors like (it is equivalent to converting a given tensor to the set structure)
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros # This is a ten_zeros tensor like the one_to_ten tensor

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Dealing with Tensor Data Types
**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Take a look at [precision in computing](https://en.wikipedia.org/wiki/Precision_(computer_science))

In [25]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None) # Even though we specify the dtype as none, it will default to torch.float32
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [26]:
# float 16 tensor
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16) # here the data type is set to float 16
float_16_tensor, float_16_tensor.dtype

(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

In [27]:
# There are two more arguments that are important for the torch.tensor() method:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what data type is the tensor (e.g. float32 or float16 being the most widely used) :: has to do with the mathematical precision \
                               # Sacrifying precision diminishes computing complexity
                               device=None, # This defaults to cpu, but "cuda" argument sends the tensor to the gpu. \
                               # Make sure that the tensors you are gonna operate with are stored on the same device
                               requires_grad=False) # Wheter or not to track gradients with this tensors' operations
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [28]:
float_16_tensor_2 = float_32_tensor.type(torch.float16)
float_32_tensor, float_32_tensor.dtype, float_16_tensor_2, float_16_tensor_2.dtype

(tensor([3., 6., 9.]),
 torch.float32,
 tensor([3., 6., 9.], dtype=torch.float16),
 torch.float16)

In [29]:
# Example of dtype mismatch during tensor operations
test_tensor = float_16_tensor * float_32_tensor
test_tensor, test_tensor.dtype # PyTorch solves some little problems that let the code run anyway, while during training you are more likely to get errors, so just be aware

(tensor([ 9., 36., 81.]), torch.float32)

In [30]:
# Even int and float datatypes might work!
int_32_tensor = torch.tensor([4,5,6], dtype=torch.int32)
int_32_tensor * float_16_tensor # Again it keeps the highest precision

tensor([12., 30., 54.], dtype=torch.float16)

### Getting information from tensors (attributes)
- Datatype - can use `tensor.dtype`
- Shape - can use `tensor.shape` (note `tensor.size()` is a method)
- Device - can use `tensor.device`

In [31]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9704, 0.5595, 0.4738, 0.4833],
        [0.5261, 0.0683, 0.9549, 0.4343],
        [0.2052, 0.1141, 0.0089, 0.4282]])

In [32]:
# Details of some_tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9704, 0.5595, 0.4738, 0.4833],
        [0.5261, 0.0683, 0.9549, 0.4343],
        [0.2052, 0.1141, 0.0089, 0.4282]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [33]:
# Some changes applied to some_tensor
some_tensor = torch.rand(size=(3,4), device="cpu") # Let's see if this works, if so, we could just as well change cpu to cuda / Yup, it worked

# Is there a reshape in torch?
some_tensor = some_tensor.reshape(shape=(4,3)) # Yes, there is

# Details of some_tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3955, 0.8850, 0.4950],
        [0.0245, 0.1421, 0.0597],
        [0.0447, 0.0704, 0.0510],
        [0.2230, 0.3806, 0.7403]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([4, 3])
Device tensor is on: cpu


### Manipulating Tensors
NN are actually a lot of tensor operations done inside the NN architecture, so Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication (dot product)

In [34]:
# Addition
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [35]:
# Multiply tensor by 10
tensor * 10 # As we don't reassign the tensor, original tensor keeps equal

tensor([10, 20, 30])

In [36]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [37]:
# Try out PyTorch built-in functions
torch.mul(tensor, 10) # 'mul' is the element-wise operator from the torch library

tensor([10, 20, 30])

In [38]:
# Same for addition
torch.add(tensor, 10) # This are supposed to run faster on a GPU when tensor's device is set to cuda

tensor([11, 12, 13])

In [39]:
# There must be one for substraction too!
torch.subtract(tensor, 10) # There ya go

tensor([-9, -8, -7])

In [40]:
# What about matrices multiplication?
torch.matmul(tensor, tensor) # I guess this is gonna give me a dimensionality error as tensor is actually a vector, so it's trying to matmul two 1x3 matrices (inner Ds mismatch)

tensor(14)

In [41]:
tensor @ tensor # wtf

tensor(14)

Turns out this solves the problem by not actually performing the matrix multiplication on the original $A.*B$ dimensions. Instead, it calculates $A.*B^T$, so it makes sense we get an scalar as a result as $(1x3) .* (1x3)$ [incompatible 3x1 inner Dimensions] is thus converted to $(1x3) .* (3x1)$, resulting in 3x3 inner Ds an 1x1 outer Ds which is the same as a single value output. **Will only work with vectors**

### Matrix multiplication

Two ways to multiply matrices:
1. Element-wise multiplication
2. Matrix multiplication (probably the most used —and useful— operation)

[More on dot product](https://www.mathsisfun.com/algebra/matrix-multiplying.html)

The two rules of dot product:

1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` this won't work
* `(3,2) @ (2,3)` this will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(3,2) @ (2,3)` -> `(2,2)`

In [42]:
# Examples on matmul use
torch.matmul(torch.rand(3,10), torch.rand(10,3)) # Results in (3,3) matrix

tensor([[1.6025, 1.6583, 1.5889],
        [2.6897, 2.3246, 2.3338],
        [3.1338, 3.0967, 3.6109]])

In [43]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [44]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [45]:
# Demonstration in execution time differences
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.53 ms, sys: 0 ns, total: 1.53 ms
Wall time: 1.53 ms


In [46]:
%%time
torch.matmul(tensor,tensor) # There is a big difference in running time even though we are only using a cpu

CPU times: user 97 µs, sys: 19 µs, total: 116 µs
Wall time: 120 µs


tensor(14)

### One of the most common errors in machine learning is shape errors

In [47]:
# NN has a lot of matrix multiplications, if there is a shape error it could halt the whole process
tensor_A = torch.tensor([
    [1,2],
    [3,4],
    [5,6]
])

tensor_B = torch.tensor([
    [7,10],
    [8, 11],
    [9, 12]
])

# torch.mm(tensor_A, tensor_B) is the same as torch.matmul, its an alias
tensor_A.shape, tensor_B.shape # They don't match

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our shape issues we can manipulate the shape of one of our tensors using a **transpose**.

A transpose switches the axes or dimensions of a given tensor

In [48]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [49]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [50]:
# Now our shapes should match, soooo let's see
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [51]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (Tensor aggregation)

Going from all elements to one element, or a few elements

In [52]:
# Create a tensor
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [53]:
# Find the min
torch.min(x), min(x) # Here the torch.min() will be better to use just like with most built in functions

(tensor(1), tensor(1))

In [54]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [55]:
# Find the mean
torch.mean(x.type(dtype=torch.float32)) # This function works with float 32, so 'Long' won't work. Needs a cast

tensor(46.)

In [56]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max (argmin, argmax)

In [57]:
# Find the positional min ||find the position in tensor that has the minimum value and return its value
x[x.argmin()], x.argmin() # This will be useful when using the softmax activation function

(tensor(1), tensor(0))

In [58]:
# Find the positional max
x[x.argmax()], x.argmax()

(tensor(91), tensor(9))

## Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a given shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (`vstack`) or side by side (`hstack`)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [59]:
# Create a tensor
x = torch.arange(1., 13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [60]:
# Add an extra dimension with tensor.reshape() [The new dimensions must be compatible with the original ones, multiply your dimensions to make sure they fit]
x_reshaped = x.reshape(1,3,2,2) # x.shape = (12), 1*3*2*2 = 12
x_reshaped

tensor([[[[ 1.,  2.],
          [ 3.,  4.]],

         [[ 5.,  6.],
          [ 7.,  8.]],

         [[ 9., 10.],
          [11., 12.]]]])

In [63]:
# Change the view (Use the same memory space but handle the view from a different variable with a different dimensionality output)
z = x.view(4,3)
z, z.shape

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]]),
 torch.Size([4, 3]))

In [64]:
# Changing z changes x (bc a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.],
         [ 5.,  5.,  6.],
         [ 5.,  8.,  9.],
         [ 5., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.]))

In [68]:
# Stack tensors on top of each other (dim is a number between 0 and the number of dimensions of the input tensors)
x_stacked = torch.stack([x,x,x,x], dim=0) # kind of like using vstack
x_stacked

tensor([[ 5.,  2.,  3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.],
        [ 5.,  2.,  3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.],
        [ 5.,  2.,  3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.],
        [ 5.,  2.,  3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.]])

In [73]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1) # This is not equivalent to hstack though, as hstack would stack them as part of the same dimension
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 5.,  5.,  5.,  5.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [ 5.,  5.,  5.,  5.],
        [11., 11., 11., 11.],
        [12., 12., 12., 12.]])

In [74]:
# Using vstack and hstack
x_vs = torch.vstack([x,x,x,x])
x_hs = torch.hstack([x,x,x,x])
x_vs, x_hs

(tensor([[ 5.,  2.,  3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.],
         [ 5.,  2.,  3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.],
         [ 5.,  2.,  3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.],
         [ 5.,  2.,  3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.,  5.,  2.,
          3.,  5.,  5.,  6.,  5.,  8.,  9.,  5., 11., 12.,  5.,  2.,  3.,  5.,
          5.,  6.,  5.,  8.,  9.,  5., 11., 12.,  5.,  2.,  3.,  5.,  5.,  6.,
          5.,  8.,  9.,  5., 11., 12.]))

In [101]:
# Squeeze
# Create a tensor with 'size 1' dimensions
tensor_s = torch.arange(1,100,5)
tensor_s = tensor_s.reshape(shape=(1,1,1,10,2)) # Has three 'size 1' dimensions

# Remove all single dimensions from a target tensor
print(f"Previous tensor: {tensor_s}")
print(f"Previous shape: {tensor_s.shape}")

# Remove extra dimensions from tensor_s
print(f"\n New tensor: {tensor_s.squeeze()}")
print(f"New shape: {tensor_s.squeeze().shape}") # Has not any 'size 1' dimensions

Previous tensor: tensor([[[[[ 1,  6],
           [11, 16],
           [21, 26],
           [31, 36],
           [41, 46],
           [51, 56],
           [61, 66],
           [71, 76],
           [81, 86],
           [91, 96]]]]])
Previous shape: torch.Size([1, 1, 1, 10, 2])

 New tensor: tensor([[ 1,  6],
        [11, 16],
        [21, 26],
        [31, 36],
        [41, 46],
        [51, 56],
        [61, 66],
        [71, 76],
        [81, 86],
        [91, 96]])
New shape: torch.Size([10, 2])


In [106]:
# What about unsqueeze? Adds a single dimension to a target tensor at a specific dim
print(f"Previous target: {tensor_s}")
print(f"Previous shape: {tensor_s.shape}")

# Add an extra dimension with unsqueeze
print(f"\nNew tensor: {tensor_s.unsqueeze(dim=0)}")
print(f"New shape: {tensor_s.unsqueeze(dim=0).shape}")

Previous target: tensor([[[[[ 1,  6],
           [11, 16],
           [21, 26],
           [31, 36],
           [41, 46],
           [51, 56],
           [61, 66],
           [71, 76],
           [81, 86],
           [91, 96]]]]])
Previous shape: torch.Size([1, 1, 1, 10, 2])

New tensor: tensor([[[[[[ 1,  6],
            [11, 16],
            [21, 26],
            [31, 36],
            [41, 46],
            [51, 56],
            [61, 66],
            [71, 76],
            [81, 86],
            [91, 96]]]]]])
New shape: torch.Size([1, 1, 1, 1, 10, 2])


In [130]:
# torch.permute returns a 'view' with dimensions permuted (re arranged). Has a dims argument as the desired orden of dimensions
x_original = torch.rand(size=(224,224,3)) # Image representation for height, width, color channels

# Permute the original tensor to re arrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts access 0->1, 1->2, and 2->0

print(f"Previous shape: {x_original.shape}") # height, width, color channels
print(f"New shape: {x_permuted.shape}") # Color channels, height, width

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [131]:
x_original[-1, -1, -1]

tensor(0.7938)

In [132]:
x_original[-1, -1, -1] = 0.5400
x_original[-1, -1, -1] # So PyTorch allows value assignations

tensor(0.5400)

In [133]:
# Check the value that was changes in x_original in x_permuted
x_permuted[-1, -1, -1] # They are the same as it uses same memory, different view

tensor(0.5400)

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [120]:
# Create a tensor
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [122]:
x[0] # Index on the first bracket dim=0

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [123]:
x[0, 0] # Index on the middle bracker dim=1. Same as x[0][0]

tensor([1, 2, 3])

In [124]:
x[0,0,0] # Index on the inner dimension (dim=2) in this case the latest bracket

tensor(1)

In [136]:
# You can also use ':' to select 'all' of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [140]:
# e.g. get all value of 0th and 1st dimenions but only index 1 of the last dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [147]:
# Get all values from 0th dimensions, but only the 1st value of dimensions 1 and 2
x[:, 0, 0]

tensor([1])

In [148]:
x[:,0,:] # all values of 0th and 2nd dimension but only the 1st of the 1st dimension

tensor([[1, 2, 3]])

In [155]:
# Index on x to return 9, and (3,6,9)
x[:,-1,-1], x[:,:,-1]

(tensor([9]), tensor([[3, 6, 9]]))

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library, because of this PyTorch can interact with it
* NumPy -> Tensor :: `torch.from_numpy(ndarray)`
* Tensor -> NumPy :: `torch.Tensor.numpy()`

In [157]:
# NumPy array to Tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: this could cause a dtype issue in case we get contrasting dtypes
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [159]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [161]:
torch.arange(1.0, 8.0).dtype # Torch keeeps the dtype of the np array it receives, so if you want to keep float32 use torch.from_numpy(ndarray).type(torch.MyDtype)

torch.float32

In [162]:
# If we use torch.from_numpy() we get a new memory space, so changing np array does not affect the tensor

# Now lets get tensor->numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [163]:
numpy_tensor.dtype, tensor.dtype

dtype('float32')